package sample.mybatis.tx.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_city
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class City {
    /**
     * Database Column Remarks:
     *   主键Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   子Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.sub_id
     *
     * @mbggenerated
     */
    private Integer subId;

    /**
     * Database Column Remarks:
     *   名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   州
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.id
     *
     * @return the value of t_city.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.id
     *
     * @param id the value for t_city.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.sub_id
     *
     * @return the value of t_city.sub_id
     *
     * @mbggenerated
     */
    public Integer getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.sub_id
     *
     * @param subId the value for t_city.sub_id
     *
     * @mbggenerated
     */
    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.name
     *
     * @return the value of t_city.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.name
     *
     * @param name the value for t_city.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.state
     *
     * @return the value of t_city.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.state
     *
     * @param state the value for t_city.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.country
     *
     * @return the value of t_city.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.country
     *
     * @param country the value for t_city.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }
}