#spring:
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      jmx-enabled: true
#      url: jdbc:mysql://localhost:3306/mybatis1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: root
#      password: 0109QWe

# 这个路径是通过 ResourceLoader加载的
# this.resourceLoader.getResource(this.properties.getConfigLocation())
#mybatis:
#  config-location: classpath:mybatis-config.xml
logging:
  level:
    root: DEBUG
#    sample:
#      mybatis:
#        mapper: TRACE

spring:
  datasource:
    txdb:
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 5000
      max-active: 100
      test-while-idle: true
      test-on-borrow: true
      jmxEnabled: true
      logValidationErrors: true
      validationQuery: SELECT 1
      url: jdbc:mysql://localhost:3306/mybatis1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      :username: root
      :password: 0109QWe

mybatis:
  rightsdb:
    mapper-locations: classpath*:sample/mybatis/mapper/*Mapper*.xml
